### PR TITLE
submit pa1-3

### PR DESCRIPTION
**Pull request by r08943099**

### CODE REVIEW

**Comment by r08943099** [comment]
@nianzelee  I don't why after I fix conflicts,  it shows all checks have failed. Please help, thanks!!

**Comment by r08943099** [comment]
@nianzelee  The error seems from 'src/ext-hello-abc/module.make', a not related file.

**Comment by Runnlion** [comment]
same situation with you, I am trying to fix it

**Comment by r08943099** [comment]
@Runnlion  How did you solve it?

**Comment by nianzelee** [comment]
@r08943099 Why did you change 2213 files? Is this necessary?

**Comment by r08943099** [comment]
@nianzelee  I don’t know why I never edit them. Should I remove them and pull requests again?

**Comment by nianzelee** [comment]
Delete them by `make clean` and push again.

**Pull request closed without merging**
